### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by fivdi** [adafruit/node_mpr121#1]
The [installation instructions](https://github.com/adafruit/node_mpr121#installation) say that node_mpr121 can be installed with `npm install mpr121`. However, this results in the installation of a [different package](https://www.npmjs.com/package/mpr121).

**Comment by toddtreece** [comment]
sorry. this started as a fork of another module and it diverged enough where it no longer made sense to issue a pull request, but i might do that still if it is useful to others.

try this for now:

```
npm install adafruit/node_mpr121
```

fixed by 06bef9c1b279085fdca5cfc57d3a1ae70df9651e

**Comment by fivdi** [comment]
Yes, `npm install adafruit/node_mpr121` installs the correct package.

**Comment by toddtreece** [comment]
thanks for catching that!

**Comment by fivdi** [comment]
No problem :)
I'll try it out when when [this](https://www.adafruit.com/products/1982) arrives in the post.
