### ISSUE TITLE
Need to run as root?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [adafruit/node_mpr121#6]
When I run this inside Docker on Pi Zero with "--privileged", it works and I can register touches.

Without docker, I run as non-root and get "Input/output error errno: 5, code: 'EIO', syscall: 'writeByte'". Same when I try to use sudo. I haven't tried root yet.

Is there a standard approach when running this with Node, to get all the right privileges turned on, without just giving up and running as root?

**Comment by dhalbert** [comment]
This problem is not specific to node, but is true of any program that tries to access the GPIO pins. However, as of Raspbian version "jessie", you can add users to the group `gpio`, and then they should be able to access the GPIO pins without needing to be root.

**Comment by GeoffreyPlitt** [comment]
Thanks!
