### ISSUE TITLE
TypeError: domain.enter is not a function

### ISSUE THREAD

**Issue by robmckinnon** [adafruit/node_mpr121#7]
When running example code using these dependency versions
- `adafruit-mpr121` *1.0.0*
- `i2c-bus` *1.2.5*
- `nan` *2.8.0*

I get the following error:

```
> const MPR121 = require('adafruit-mpr121'),
...       mpr121  = new MPR121(0x5A, 1);
undefined
> domain.js:120
    domain.enter();
           ^

TypeError: domain.enter is not a function
    at topLevelDomainCallback (domain.js:120:12)
```

*Hardware*: Raspberry Pi 3 B+
*OS*: Raspbian Stretch With Desktop - June 2018
*Node*: v10.11.0

Example code works successfully if I change to latest version of `i2c-bus` *4.0.2* and `nan` *2.11.1*.

So a fix is to upgrade `i2c-bus` in `package.json`:

```
"dependencies": {
    "i2c-bus": "^4.0.2"
  }
```

**Comment by robmckinnon** [comment]
This [pull request upgrades `i2c-bus`](https://github.com/adafruit/node_mpr121/pull/8) to latest version as a fix for the `domain.enter is not a function` error: https://github.com/adafruit/node_mpr121/pull/8

**Comment by ladyada** [comment]
hiya - we don't have anyone at adafruit who knows node at all... are you at all interested in maintaining/fixing this library since you seem to be using it? :)

**Comment by robmckinnon** [comment]
hiya Lady Ada, I'm honoured you asked me to maintain this library.

I'm happy to contribute fixes like this, but don't have time to be a full-time maintainer.

I've made a second PR with [detailed install steps for a Raspberry Pi](https://github.com/adafruit/node_mpr121/pull/9). Your team at adafruit should be able to follow these to confirm everything is working.

**Comment by ladyada** [comment]
ok - honestly we are not going to get around to re-testing this guide so we'll go on faith :D

**Comment by ladyada** [comment]
ok all is merged, is this issue resolved then? :)

**Comment by robmckinnon** [comment]
Resolved. Thanks.
